### ISSUE TITLE
In HTML5, the <head> element can be omitted. The zend-developer-tools css requires it.

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#1]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-developer-tools/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-developer-tools/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

In HTML5, the &lt;head&gt; element can be omitted. The following code will validate as HTML5:
```html
<!DOCTYPE html>
<html>
<title>Title of the document</title>

<body>
<h1>This is a heading</h1>
<p>This is a paragraph.</p>
</body>

</html>
```

However, ZendDeveloperTools\Listener->injectToolbar() requires it to work
```php
$injected = preg_replace('/<\/head>/i', $style . "\n</head>", $injected, 1);
```

### Expected results

Styles should be displayed in the html document even if there is no &lt;head&gt; html element when the document is html 5 document.

### Actual results

html document does not include zend-developer-tools required css, if &lt;head&gt; element is missing from the layout.

---

Originally posted by @villetikkanen at https://github.com/zendframework/zend-developer-tools/issues/255

**Comment by samsonasik** [comment]
@villetikkanen I've created PR https://github.com/laminas/laminas-developer-tools/pull/31 for it.
