### ISSUE TITLE
Whitespace Bleed

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#12]
The toolbar bleeds 8 new lines into each response, which can cause issues (if, for example, you try and build a zip file then those 8 new lines will be included in that zip file causing it to be invalid).

Could this be fixed?

---

Originally posted by @PatrickRose at https://github.com/zendframework/zend-developer-tools/issues/162

**Comment by weierophinney** [comment]
@PatrickRose the toolbar should only interfere when the output is `text/html`. Could you elaborate a bit on this issue?


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/162#issuecomment-52648732

**Comment by weierophinney** [comment]
I'd need to delve deep into our source code to try and find the issue involved with download (though I'll grab the person involved when they come in).

I can spot it in our API requests though, and although it's not a real issue there it does irk me slightly.


---

Originally posted by @PatrickRose at https://github.com/zendframework/zend-developer-tools/issues/162#issuecomment-52747796

**Comment by weierophinney** [comment]
Our download action uses the `Zend\Http\Response\Stream` object to stream the contents of the file, and we set the Content-Type to `application/x-gzip`. 


---

Originally posted by @PatrickRose at https://github.com/zendframework/zend-developer-tools/issues/162#issuecomment-52888441

**Comment by weierophinney** [comment]
@PatrickRose Any update on this?


---

Originally posted by @moderndeveloperllc at https://github.com/zendframework/zend-developer-tools/issues/162#issuecomment-69347135

**Comment by weierophinney** [comment]
I no longer work at the place where I encountered - but a message to the staff there says its still an issue.


---

Originally posted by @PatrickRose at https://github.com/zendframework/zend-developer-tools/issues/162#issuecomment-69370305

**Comment by weierophinney** [comment]
Just downloading the ZF2 application skeleton and adding a download action to the index controller w/ the mentioned stream and type isn't enough to reproduce the issue. I had Zend Developer Tools installed via Composer and in the application config.

``` php
    // This should be an array of module namespaces used in the application.
    'modules' => array(
        'Application',
        'ZendDeveloperTools',
    ),
```

Here's the code I used when I attempted to reproduce this issue.

``` php
    public function downloadAction()
    {
        $fileName = '/vagrant/somefile.tar.gz';
        $basename = basename($fileName);

        $response = new Stream();
        $response->setStream(fopen($fileName, 'r'));
        $response->setStatusCode(200);
        $response->setStreamName($basename);

        $headers = new Headers();
        $headers->addHeaders(array(
            'Content-Disposition' => 'attachment; filename="' . $basename . '"',
            'Content-Type' => 'application/x-gzip',
            'Content-Length' => filesize($fileName),
        ));
        $response->setHeaders($headers);
        return $response;
    }
```

I managed to download a working `.tar.gz` file. When I tested it using the answers in [this StackOverflow question](http://stackoverflow.com/questions/2001709/how-to-check-if-a-unix-tar-gz-file-is-a-valid-file-without-uncompressing) and compared it with various header parameters, the file still appeared to be fine when the `Content-Disposition` parameter was properly specified.


---

Originally posted by @Barbarrosa at https://github.com/zendframework/zend-developer-tools/issues/162#issuecomment-75480818

**Comment by samsonasik** [comment]
I tried in latest laminas-developer-tools to download zip and tar.gz file, both working fine. I am closing it.
