### ISSUE TITLE
ZendDeveloperTools conflicts with Zend\Code 2.3.1 and 2.2.7

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#15]
See zendframework/zf2#6166

Resolution is to wait for the next release (2.2.8 and 2.3.2) and then remove the patched code at https://github.com/zendframework/ZendDeveloperTools/blob/9f93faecc1c9c31b8af67491f0e706e75b1f85bf/src/ZendDeveloperTools/Listener/EventLoggingListenerAggregate.php#L120

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/148

**Comment by weierophinney** [comment]
@Ocramius What about to add a `conflict` entry in composer?

https://getcomposer.org/doc/04-schema.md#conflict


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-developer-tools/issues/148#issuecomment-41075747

**Comment by weierophinney** [comment]
@Maks3w it actually conflicts with previous versions as well because of #147
I really must wait for a new zf2 release and then bump the minimum version before tagging.


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/148#issuecomment-41080714

**Comment by samsonasik** [comment]
it seems no longer relevant. closing.
