### ISSUE TITLE
Problem with zend-eventmanager 3.x

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#2]
As described in doctrine/DoctrineORMModule#567 there is a problem with zend-eventmanager 3.x.

The [`trigger()`](https://github.com/zendframework/ZendDeveloperTools/blob/master/src/Module.php#L63) method is not fully compatible with zend-eventmanager 3.x.

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-developer-tools/issues/244

**Comment by weierophinney** [comment]
This needs a fix.

---

Originally posted by @kaidoj at https://github.com/zendframework/zend-developer-tools/issues/244#issuecomment-406500267

**Comment by samsonasik** [comment]
I tried with latest `DoctrineORMModule` and it seems working ok. 

![Screen Shot 2020-07-15 at 10 34 18 AM](https://user-images.githubusercontent.com/459648/87500488-c61e1900-c686-11ea-96de-7b33b8711eeb.png)

Closing.
