### ISSUE TITLE
Modules list should have vertical scrolling

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#21]
Mine does not fit panel height (4 modules are missed at the bottom)

![screen shot 2013-07-09 at 4 56 40 pm](https://f.cloud.github.com/assets/173697/768121/bb57d49a-e897-11e2-9c62-97ecbae2b51f.png)

---

Originally posted by @vgarvardt at https://github.com/zendframework/zend-developer-tools/issues/115

**Comment by samsonasik** [comment]
It is already vertical scrolling now.

![Screen Shot 2020-07-24 at 6 09 16 PM](https://user-images.githubusercontent.com/459648/88385593-d34eac80-cdd8-11ea-8f2e-0586b128ccba.png)

I am closing it.
