### ISSUE TITLE
default template suffix

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#23]
Using composer to install zf2 skeleton along with developer tools. After enabling it I am getting server errors, like:

```
PHP Fatal error:  Uncaught exception 'Zend\\View\\Exception\\RuntimeException' with message 'Zend\\View\\Renderer\\PhpRenderer::render: Unable to render template "zend-developer-tools/toolbar/zendframework"; resolver could not resolve to a file' in C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zendframework\\library\\Zend\\View\\Renderer\\PhpRenderer.php:499
Stack trace:
#0 C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zend-developer-tools\\src\\ZendDeveloperTools\\Listener\\ToolbarListener.php(203): Zend\\View\\Renderer\\PhpRenderer->render(Object(Zend\\View\\Model\\ViewModel))
#1 C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zend-developer-tools\\src\\ZendDeveloperTools\\Listener\\ToolbarListener.php(148): ZendDeveloperTools\\Listener\\ToolbarListener->renderEntries(Object(ZendDeveloperTools\\ProfilerEvent))
#2 C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zend-developer-tools\\src\\ZendDeveloperTools\\Listener\\ToolbarListener.php(137): ZendDeveloperTools\\Listener\\ToolbarListener->injectToolbar(Object(ZendDe in C:\\Users\\Milan\\workspace\\HopkaupZEND\\vendor\\zendframework\\zendframework\\library\\Zend\\View\\Renderer\\PhpRenderer.php on line 499
```

adding 'default_template_suffix' key to module.config.php:

``` php
return array(
    'view_manager' => array(
        'default_template_suffix' => 'phtml',
        'template_path_stack' => array(
            'zenddevelopertools' => __DIR__ . '/../view',
        ),
    ),
);
```

fixes the issue.

---

Originally posted by @minow at https://github.com/zendframework/zend-developer-tools/issues/94

**Comment by weierophinney** [comment]
I got a similar issue, would you please help me solve it?
Thanks!
![untitled](https://f.cloud.github.com/assets/6925456/2406211/1b12cba2-aa66-11e3-83fc-13998fd94b91.JPG)


---

Originally posted by @jerrybk108 at https://github.com/zendframework/zend-developer-tools/issues/94#issuecomment-37498924

**Comment by weierophinney** [comment]
We cannot enforce the default template suffix within ZDT, as it would override any settings provided by other users.


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/94#issuecomment-37534966

**Comment by weierophinney** [comment]
Actually, this can be fixed by providing a direct template map, instead of a template path stack.


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/94#issuecomment-37536071

**Comment by weierophinney** [comment]
in my case i fix it through:
//            'zenddevelopertools' => **DIR** . '/../view',
            'ZendDeveloperTools' => **DIR** . '/../view',
in config/autload/config.php


---

Originally posted by @findli at https://github.com/zendframework/zend-developer-tools/issues/94#issuecomment-102955994

**Comment by samsonasik** [comment]
Should be fixed now since path is now same with view directory with dashed separator. Please re-create issue if problem persist. Closing.
