### ISSUE TITLE
Uncaught ReferenceError: Sfdump is not defined

### ISSUE THREAD

**Issue by FraGoTe** [laminas/laminas-developer-tools#29]
I'm getting the following JS errors:

![image](https://user-images.githubusercontent.com/1095778/72657176-3f0a1580-396f-11ea-9a24-0e9724985a4f.png)

**Comment by CreativeNative** [comment]
Me too. Any updates here?

**Comment by criterion9** [comment]
Any idea when this fix will make it into a release?

**Comment by michalbundyra** [comment]
@criterion9 "soon". We have already PR #28. If we get there some test it will help a lot, but it's on my list for that week.

**Comment by michalbundyra** [comment]
Thanks for reporting. I've released versions with the hotfix: 1.3.1 and 2.0.1.
