### ISSUE TITLE
Support for zend-expressive

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#3]
Is there any plan to support zend-expressive as well ?

PS: see also https://github.com/zendframework/zend-expressive-skeleton/issues/157

---

Originally posted by @belgattitude at https://github.com/zendframework/zend-developer-tools/issues/241

**Comment by samsonasik** [comment]
there is php-middleware/php-debug-bar for that https://docs.mezzio.dev/mezzio/v3/cookbook/debug-toolbars/ . While the installation is still need a tweak after follow documentation (need manual copy assets), that works.
