### ISSUE TITLE
ZendDeveloperTools is not compatible with Session in ZF <= 2.3.1

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-developer-tools#9]
Says "Session Validation Failed" on SessionManager->start() (used in FlashMessenger...)

<img width="989" alt="capture d ecran 2015-10-22 a 20 28 02" src="https://cloud.githubusercontent.com/assets/1698236/10674526/aad9a296-78fb-11e5-81c7-e17a4409447f.png">

---

Originally posted by @bioub at https://github.com/zendframework/zend-developer-tools/issues/197

**Comment by weierophinney** [comment]
Should raise dependency to ZF 2.4+.
On Oct 22, 2015 11:31 AM, "Romain Bohdanowicz" notifications@github.com
wrote:

> Says "Session Validation Failed" on SessionManager->start() (used in
> FlashMessenger...)
> 
> [image: capture d ecran 2015-10-22 a 20 28 02]
> https://cloud.githubusercontent.com/assets/1698236/10674526/aad9a296-78fb-11e5-81c7-e17a4409447f.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zendframework/ZendDeveloperTools/issues/197.


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/197#issuecomment-150805004

**Comment by weierophinney** [comment]
Then maybe you should add some stable tags ? One for ZF 2.0 to ZF 2.3, another for ZF 2.4+, my client wasn't able to upgrade it's PHP version which was PHP 5.3.3 so had to keep ZF 2.2.10.


---

Originally posted by @bioub at https://github.com/zendframework/zend-developer-tools/issues/197#issuecomment-150912970

**Comment by weierophinney** [comment]
Can't tackle this atm, but I see that @samsonasik already asked for more tags :-\


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-developer-tools/issues/197#issuecomment-150913021

**Comment by samsonasik** [comment]
seems no longer relevant. closing.
